Feature/accounts edit and delete
NIAEFEUP/website-niaefeup-backend pull request #108
Opened 2023-02-10 10:17 UTC by CarlosMealha

Closes #93 

Adds endpoints to edit and delete accounts 

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [ ] Contains enough appropriate tests
-   [ ] Behavior is as expected
-   [x] Clean, well structured code

2023-02-10 10:36 UTC, CarlosMealha commented
Can someone tell me how I can work around the error of using wildcard imports, because in these two cases ```
import jakarta.persistence.*
import org.junit.jupiter.api.*
```, when I individually import, it automatically gives a fix for `*`

2023-02-11 10:40 UTC, CarlosMealha commented
> Can someone tell me how I can work around the error of using wildcard imports, because in these two cases `import jakarta.persistence.* import org.junit.jupiter.api.*`, when I individually import, it automatically gives a fix for `*`

So I removed the IDE flag that blocked wildcard imports and added a comment to the README file.

2023-02-12 00:25 UTC, BrunoRosendo commented
There are still some linting problems (you can fix them automatically, check readme or just format with the plugin). You also need to rebase now

2023-02-12 11:13 UTC, CarlosMealha commented
> There are still some linting problems (you can fix them automatically, check readme or just format with the plugin). You also need to rebase now

Yes I know that, I'm currently testing the edit endpoint and then I will fix that

2023-02-22 17:29 UTC, gui1612 commented
Things seem to be working from an high level. Can you explain again what the problem was @CarlosMealha?
Just linting issues?

2023-02-22 17:35 UTC, CarlosMealha commented
> Things seem to be working from an high level. Can you explain again what the problem was @CarlosMealha?
> Just linting issues?

Yes everything is working, just need to finish testing the edit endpoint, at the moment one of the atributtes is not being changed to the expected one.

2023-03-17 22:46 UTC, BrunoRosendo requested changes
I don't think it makes sense to allow for password change here. We already have an endpoint for changing passwords and that operation required sending the old password as well.

I see 2 options:
- Remove the password field from this endpoint (new dto for example)
- Port the password change logic into this endpoint. I'm not the biggest fan of this approach, since the logic is different from a normal update, but I understand its advantages.

What do you think?

2023-03-29 19:51 UTC, BrunoRosendo requested changes

2023-03-29 19:51 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/service/AccountService.kt
> +        )
There should be no need to do this, UpdateAccountDto can extend EntityDto

2023-03-29 19:51 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/service/AccountService.kt
> +    }
We shouldn't return emptyMap() in the service (we changed this recently). Services should not handle API responses, that's for controllers

2023-03-29 19:51 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/dto/account/UpdateAccountDto.kt
> +class UpdateAccountDto(
It might be confusing to have AccountDto when it's only used for creating it. I suggest changing it to CreateAccountDto (similarly to update)

2023-03-29 19:51 UTC, BrunoRosendo commented on src/test/kotlin/pt/up/fe/ni/website/backend/controller/AccountControllerTest.kt
> +        fun `should fail if the project does not exist`() {
```suggestion
        fun `should fail if the account does not exist`() {
```

2023-04-05 14:15 UTC, MRita443 commented
Ever since my latest commit, I have been getting test failures on both `/posts/{postSlug}` and `/posts/{postId}`. I haven't changed these tests, and the errors I am getting are due to `lastUpdatedAt` being an hour earlier than expected. For example:
`JSON path "$.lastUpdatedAt" expected:<05-04-2023 15:07:09> but was:<05-04-2023 14:07:09>`. Can anyone tell me if this is normal and why this seems to be happening?

2023-04-05 18:34 UTC, BrunoRosendo commented
> Ever since my latest commit, I have been getting test failures on both `/posts/{postSlug}` and `/posts/{postId}`. I haven't changed these tests, and the errors I am getting are due to `lastUpdatedAt` being an hour earlier than expected. For example: `JSON path "$.lastUpdatedAt" expected:<05-04-2023 15:07:09> but was:<05-04-2023 14:07:09>`. Can anyone tell me if this is normal and why this seems to be happening?

That seems to be a local problem related to the daylight saving time that changed last week. Can you try putting this setting in application.properties and see if it changes? `spring.jackson.time-zone=UTC`

2023-04-05 18:36 UTC, BrunoRosendo commented
@MRita443 Actually, you might want to try it in the `toJson()` extension function at the end of the test file, depending on whether the timezone is wrong in the application (`but was`) or the test (`expected`)

2023-04-05 18:38 UTC, BrunoRosendo approved these changes
Good job!

2023-04-05 19:40 UTC, LuisDuarte1 approved these changes
LGTM 🚀🚀 🚀 🚀 🚀 🚀 🚀

2023-04-05 21:59 UTC, merged