Add email service
NIAEFEUP/website-niaefeup-backend pull request #123
Opened 2023-02-23 22:38 UTC by ttoino

Closes #82.

Adds a new `EmailService` with a method `send`, which receives an instance of `EmailBuilder`.
Two builders were implemented: `SimpleEmailBuilder`, which receives all properties directly, and `TemplateEmailBuilder`, which generates the subject and content from the given data using mustache templates.

Each different template email should be a subclass of `TemplateEmailBuilder`, here's an example:

```kotlin
data class ExampleContext(
    val title: String,
    val todos: List<String>
)

class ExampleEmailBuilder : TemplateEmailBuilder<ExampleContext>() {
    override val textTemplatePath = "example.txt"
    override val htmlTemplatePath = "example.html"
    override fun subject(data: ExampleContext?): String = "Example: ${data?.title}"
}
```

```html

{{>head.html}}

<h1>{{title}}</h1>

<ul>
    {{#todos}}
        <li>{{.}}</li>
    {{/todos}}
</ul>

{{>foot.html}}

# {{title}}

{{#todos}}
- {{.}}
{{/todos}}
```

```kotlin
service.send(
    ExampleEmailBuilder()
        .data(ExampleContext("Grocery list", listOf("Potatoes", "Tomatoes", "Cheese")))
        .to("email@email.com")
)
```

This sends an email that looks something like this:

![image](https://user-images.githubusercontent.com/14280476/221046493-a1091651-afa3-4b15-8b78-ac6716e451d4.png)
![image](https://user-images.githubusercontent.com/14280476/221046525-bcee3c5a-898c-48cd-b9b9-89a3408ac176.png)
![image](https://user-images.githubusercontent.com/14280476/221046552-c544df71-e47c-4ad3-99a7-b472953b686b.png)

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [ ] Contains enough appropriate tests
-   [ ] Behavior is as expected
-   [ ] Clean, well structured code

2023-02-23 22:51 UTC, ttoino commented
Not sure why the tests are failing... Probably need to configure something to mock the java mail sender

2023-03-04 01:48 UTC, ttoino commented
I'm marking as ready for review, but a few things are still missing:

- [ ] Support for images and other embedded resources like styles
- [ ] Default email layout and styles
- [ ] Some kind of testing (not sure what to do here)
- [ ] Maybe markdown support (markdown is sent with minimal edits for the plain text version and converted to html for the html version)

2023-03-19 18:10 UTC, BrunoRosendo requested changes
What a great PR 🎉 Tremendous job! I left minor/cosmetic suggestions

One thing I don't like is having `email` as a top-level package, I think we already have enough of them. What do you think of storing the builders under `service/email/`? together with EmailService?

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/config/email/EmailConfigProperties.kt
> +    val fromPersonal: String = from,
What is `fromPersonal`? The name that's displayed?

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/BaseEmailBuilder.kt
> +    fun from(@Email email: String, personal: String = email) = apply {
Great use of the `apply` function!

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/BaseEmailBuilder.kt
> +abstract class BaseEmailBuilder : EmailBuilder {
Testing the builders should be trivial with unit tests (testing validation, whether emails are added in the right places, etc.)

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    }
```suggestion
    override fun build(helper: MimeMessageHelper, emailConfigProperties: EmailConfigProperties) {
        super.build(helper, emailConfigProperties)

        text?.let { helper.setText(it, html ?: false) }
        html?.let { helper.setText(it, true) }

        subject?.let { helper.setSubject(it) }

        attachments.forEach { helper.addAttachment(it.name, it.content) }
        inlines.forEach { helper.addInline(it.name, it.content) }
    }
```
I asked chatGPT to simplify this function, wdyt? 😛

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/TemplateEmailBuilder.kt
> +    }
There's a world where we could have these renderers/parsers as beans in our `config/email` and use Spring's dependency injection (`@AutoWired`/`@Component` if possible or `ApplicationContextUtils` otherwise). Still, this is a very simple config so I don't think it's a big deal if it resides here

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/resources/email/style.css
> +*/
New issue?

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/service/EmailService.kt
> +    val emailConfigProperties: EmailConfigProperties
why is this one public?

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/TemplateEmailBuilder.kt
> +    override fun build(helper: MimeMessageHelper, emailConfigProperties: EmailConfigProperties) {
this function is a bit verbose, I'd consider splitting it into more methods if possible

2023-03-19 18:10 UTC, BrunoRosendo commented on src/main/resources/application.properties
> +spring.mail.password=
Will we need to configure this in prod? It'd be nice to have some example on the wiki if so

2023-03-19 18:11 UTC, BrunoRosendo commented on src/main/resources/templates/email/layout.html.mustache
> +    <!-- TODO -->
perhaps another issue

2023-03-20 14:30 UTC, ttoino commented on src/main/resources/templates/email/layout.html.mustache
> +    <!-- TODO -->
Done!

2023-03-20 14:31 UTC, ttoino commented on src/main/resources/email/style.css
> +*/
Done!

2023-03-20 14:32 UTC, ttoino commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    }
I think the text and html lines need to be swapped, but it definitely looks cleaner.

2023-03-20 14:35 UTC, ttoino commented on src/main/kotlin/pt/up/fe/ni/website/backend/config/email/EmailConfigProperties.kt
> +    val fromPersonal: String = from,
Yeah, `personal` is the name that javamail uses for that.

2023-03-20 14:36 UTC, ttoino commented on src/main/kotlin/pt/up/fe/ni/website/backend/service/EmailService.kt
> +    val emailConfigProperties: EmailConfigProperties
No clue, it should probably be private too :sweat_smile:

2023-03-20 14:36 UTC, ttoino commented on src/main/resources/application.properties
> +spring.mail.password=
You're right, I'll add a section on how to configure it

2023-03-20 14:38 UTC, ttoino commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/TemplateEmailBuilder.kt
> +    }
I thought about it but I'm still unsure about some parts of the bean system, I'll try to look into it further

2023-03-20 14:46 UTC, ttoino commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    }
Actually, the compiler does not seem to like the `html ?: false` expression, both sides probably need to be of the same type

2023-03-20 17:19 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    }
I see, I'll let you decide if there's anything that can be improved

2023-03-20 17:20 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/TemplateEmailBuilder.kt
> +    }
beans are basically singletons you can request anywhere in the app, so you should have the same result but the singletons will all be handled by Spring and the respective configuration would be in `config/` package

2023-04-01 17:53 UTC, BrunoRosendo commented on src/main/resources/application.properties
> +spring.mail.password=
Where is it? I may be legally blind

2023-04-02 01:09 UTC, BrunoRosendo commented
Have you decided something about the tests?

2023-07-03 16:16 UTC, bdmendes commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    private var inlines: MutableList<EmailFile> = mutableListOf()
What are inlines?

2023-07-03 16:28 UTC, ttoino commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    private var inlines: MutableList<EmailFile> = mutableListOf()
An inline is a file that is sent along with an email, similar to an attachment, except it doesn't show as a downloadable file and instead can be referenced from the email html using the `cid:` protocol. This is how inline images are implemented.

2023-07-03 20:09 UTC, bdmendes commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilder.kt
> +    private var inlines: MutableList<EmailFile> = mutableListOf()
Oh, nice. Maybe we should have a comment explaining that since I'm guessing a lot of people won't know that.

2023-09-01 14:22 UTC, DoStini commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/BaseEmailBuilder.kt
> +abstract class BaseEmailBuilder : EmailBuilder {
One can also mock the java mail library and verify if the methods are being called with the correct arguments

2025-01-24 17:46 UTC, MRita443 requested changes
It's looking good so far. Shouldn't we add tests for `SimpleEmailBuilder` and `TemplateEmailBuilder`too?

2025-01-24 17:46 UTC, MRita443 commented on src/main/resources/application.properties
> +spring.mail.password=
Could you try to add this @rubuy-74 ?

2025-01-24 17:46 UTC, MRita443 commented on src/test/kotlin/pt/up/fe/ni/website/backend/email/BaseEmailBuilderTest.kt
> +}
Why is this needed?

2025-01-26 16:13 UTC, rubuy-74 commented
Don't forget to add instruction for testing on the wiki.

2025-02-03 00:12 UTC, BrunoRosendo reviewed
I like the changes from the last time I saw it. Good job with the tests!

One thing that would be great to improve is the size of the PRs. We didn't use to do this in NI but it's much easier to do small and incremental PRs, even if the feature or issue isn't fully closed. This should help make the reviews quicker and avoid having stale CRs for months at a time

PS: you need to fix the lint, it seems

2025-02-03 00:14 UTC, BrunoRosendo approved these changes
approve to unblock, but look at the comments

2025-02-18 18:00 UTC, MRita443 requested changes
Great job with the tests! There's some simple errors as of now if you could fix that. And don't forget the lint and comments here

2025-02-18 18:00 UTC, MRita443 commented on src/test/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilderTest.kt
> +            Mockito.lenient().`when`(from).thenReturn("test@email.com")
Why did you use lenient?

2025-02-18 18:00 UTC, MRita443 commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/ExampleEmailBuilder.kt
Reminder to delete this after putting it on the wiki

2025-02-27 15:18 UTC, rubuy-74 commented on src/main/resources/application.properties
> +spring.mail.password=
There is now a section of the wiki explaining how to setup these variables and create a sample email sending service.

https://github.com/NIAEFEUP/website-niaefeup-backend/wiki/Sending-Emails#testing

2025-02-27 15:23 UTC, rubuy-74 commented on src/test/kotlin/pt/up/fe/ni/website/backend/email/SimpleEmailBuilderTest.kt
> +            Mockito.lenient().`when`(from).thenReturn("test@email.com")
These variables are not used in all of the tests and as the Mockito Library is very strict in terms of used Mocked variables. 

https://stackoverflow.com/questions/60420191/mockito-lenient-when-to-use

To avoid the error, the lenient function is used. I'll add this as a comment above the test.

2025-02-27 15:40 UTC, rubuy-74 commented on src/test/kotlin/pt/up/fe/ni/website/backend/email/BaseEmailBuilderTest.kt
> +}
In the BaseEmailBuilder class, there are no getters and there is no need to access the attributes of the instance outside of the tests. So, implementing a wrapper class that has the getters seemed like the best idea.

2025-02-27 15:41 UTC, rubuy-74 commented on src/main/kotlin/pt/up/fe/ni/website/backend/email/ExampleEmailBuilder.kt
Thank you :smile:

2025-03-09 15:00 UTC, MRita443 approved these changes
Great job! A comment for posteriority: If the email tests and application context load fails, delete the `website-be-h2-db.mv.db` file in your home folder

2025-03-09 15:12 UTC, merged