Feature/activities slug
NIAEFEUP/website-niaefeup-backend pull request #94
Opened 2023-01-31 21:20 UTC by jamcunha

Closes #76 

Similar to #75, I added an optional slug to the activities.

# Review checklist
-   [ ] Properly documents API changes in `docs/openapi.yml`
-   [x] Contains enough appropriate tests
-   [x] Behavior is as expected
-   [ ] Clean, well structured code

2023-02-01 00:49 UTC, BrunoRosendo requested changes
Good job! But aren't we missing the getBySlug endpoint for events?

2023-02-01 00:49 UTC, BrunoRosendo commented on src/main/kotlin/pt/up/fe/ni/website/backend/service/ProjectService.kt
> +        }
#55 needs to take this into consideration for the events

2023-02-01 00:49 UTC, BrunoRosendo commented on src/test/kotlin/pt/up/fe/ni/website/backend/controller/EventControllerTest.kt
> +                    "slug" to testEvent.slug
Do we need this? Slug is not required

2023-02-02 15:59 UTC, BrunoRosendo approved these changes
Looks good! You just need to rebase it with latest changes in develop

2023-02-03 23:30 UTC, BrunoRosendo approved these changes

2023-02-07 16:14 UTC, bdmendes reviewed
Good job! I have a small suggestion. Since both projects and events services and repositories are accessing the slug in the exact same way, what do you think of introducing an abstract `ActivityRepository` (and service)?

2023-02-07 16:20 UTC, MRita443 commented
> Good job! I have a small suggestion. Since both projects and events services and repositories are accessing the slug in the exact same way, what do you think of introducing an abstract `ActivityRepository` (and service)?

I implemented a similar solution in #89, check it out to see if it's what you suggested!

2023-02-07 16:32 UTC, bdmendes commented
> > Good job! I have a small suggestion. Since both projects and events services and repositories are accessing the slug in the exact same way, what do you think of introducing an abstract `ActivityRepository` (and service)?
> 
> I implemented a similar solution in #89, check it out to see if it's what you suggested!

I like it! I would just make it a bit more cohesive by using inheritance.

2023-02-07 19:30 UTC, BrunoRosendo commented
> > > Good job! I have a small suggestion. Since both projects and events services and repositories are accessing the slug in the exact same way, what do you think of introducing an abstract `ActivityRepository` (and service)?
> > 
> > 
> > I implemented a similar solution in #89, check it out to see if it's what you suggested!
> 
> I like it! I would just make it a bit more cohesive by using inheritance.

Maybe we should wait for #89 merge then. Inheritance might be trickier but it'd be nice to look at an implementation of that

2023-02-23 14:16 UTC, bdmendes reviewed
Looks good to me. However, I thought that the slug was intended to be an internal small representation of the title (perhaps with some parts of the date and/or description) and should be generated automatically upon creating the activity. Would not that be a better approach than the optional?

2023-02-23 15:53 UTC, jamcunha commented
> Looks good to me. However, I thought that the slug was intended to be a small internal representation of the title (perhaps with some parts of the date and/or description) and should be generated automatically upon creating the activity. Would not that be a better approach than the optional one?

We agreed in #75 that the slug would be generated in the frontend, giving the option to write another slug if wanted.

2023-02-24 09:30 UTC, bdmendes commented
Awesome, let's get this merged then

2023-02-24 09:30 UTC, bdmendes approved these changes

2023-02-24 09:30 UTC, merged